In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import warnings
import seaborn as sns
warnings.filterwarnings('ignore')
sns.set_style('whitegrid')
#

In [2]:
adult = pd.read_csv('../data/adult.data', header=None)
adult.head(5)

   0                  1       2           3   ...  11  12              13      14
0  39          State-gov   77516   Bachelors  ...   0  40   United-States   <=50K
1  50   Self-emp-not-inc   83311   Bachelors  ...   0  13   United-States   <=50K
2  38            Private  215646     HS-grad  ...   0  40   United-States   <=50K
3  53            Private  234721        11th  ...   0  40   United-States   <=50K
4  28            Private  338409   Bachelors  ...   0  40            Cuba   <=50K

[5 rows x 15 columns]

In [3]:
adult.shape

(32561, 15)

In [4]:
adult.columns

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], dtype='int64')

In [5]:
adult = adult.rename(columns={0:'Age', 1:'Workclass', 2:'Fnlwgt', 3:'Education', 4:'Education_num',
                              5:'marital_status', 6:'Occupation', 7:'Relationship',
                              8:'Race', 9:'Sex', 10:'capital_gain', 11:'capital_loss', 12:'hours_per_week',
                              13:'Country', 14:'Income'})
adult.head(5)

   Age          Workclass  Fnlwgt  ... hours_per_week         Country  Income
0   39          State-gov   77516  ...             40   United-States   <=50K
1   50   Self-emp-not-inc   83311  ...             13   United-States   <=50K
2   38            Private  215646  ...             40   United-States   <=50K
3   53            Private  234721  ...             40   United-States   <=50K
4   28            Private  338409  ...             40            Cuba   <=50K

[5 rows x 15 columns]

In [6]:
adult['Education_num'].value_counts()

Education_num
9     10501
10     7291
13     5355
14     1723
11     1382
7      1175
12     1067
6       933
4       646
15      576
5       514
8       433
16      413
3       333
2       168
1        51
Name: count, dtype: int64

In [7]:
adult['Education'].value_counts()

Education
HS-grad         10501
Some-college     7291
Bachelors        5355
Masters          1723
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           646
Prof-school       576
9th               514
12th              433
Doctorate         413
5th-6th           333
1st-4th           168
Preschool          51
Name: count, dtype: int64

In [8]:
adult = adult.drop(columns=['Education'])

In [9]:
adult['Income'].value_counts()

Income
<=50K    24720
>50K      7841
Name: count, dtype: int64

In [10]:
adult['Income'] = adult['Income'].str.strip()
adult['Income'] = adult['Income'].replace(['<=50K', '>50K'], [0, 1]).astype(int)
adult['Income'].value_counts()

Income
0    24720
1     7841
Name: count, dtype: int64

In [11]:
adult['Sex'].value_counts()

Sex
Male      21790
Female    10771
Name: count, dtype: int64

In [12]:
adult['Sex'] = adult['Sex'].str.strip().map({'Male': 1, 'Female': 0})
print("Value counts for encoded 'Sex' column:")
display(adult['Sex'].value_counts())

Value counts for encoded 'Sex' column:

Sex
1    21790
0    10771
Name: count, dtype: int64

In [13]:
print("Number of duplicates: ", adult.duplicated().sum())
adult.drop_duplicates(inplace=True)

Number of duplicates:  24

In [14]:
categorical_cols = adult.select_dtypes(include='object').columns

for col in categorical_cols:
    if ' ?' in adult[col].unique():
        print(f"  -> Found '?' in column '{col}'. This might indicate missing values.")

  -> Found '?' in column 'Workclass'. This might indicate missing values.
  -> Found '?' in column 'Occupation'. This might indicate missing values.
  -> Found '?' in column 'Country'. This might indicate missing values.

In [15]:
import numpy as np

for col in ['Workclass', 'Occupation', 'Country']:
    adult[col] = adult[col].replace(' ?', np.nan)
    # Impute missing values with the mode
    mode_value = adult[col].mode()[0]
    adult[col] = adult[col].fillna(mode_value) # Fixed: Removed inplace=True and assigned back
    print(f"Missing values in '{col}' after imputation: {adult[col].isnull().sum()}")

Missing values in 'Workclass' after imputation: 0
Missing values in 'Occupation' after imputation: 0
Missing values in 'Country' after imputation: 0

In [16]:
numerical_cols = adult.select_dtypes(include=np.number).columns

plt.figure(figsize=(15, 10))
for i, col in enumerate(numerical_cols):
    plt.subplot(3, 3, i + 1) # Adjust subplot grid as needed
    adult[col].hist(bins=20)
    plt.title(col)
    plt.xlabel('')
plt.tight_layout()
plt.show()

In [17]:
adult.describe()

                Age        Fnlwgt  ...  hours_per_week        Income
count  32537.000000  3.253700e+04  ...    32537.000000  32537.000000
mean      38.585549  1.897808e+05  ...       40.440329      0.240926
std       13.637984  1.055565e+05  ...       12.346889      0.427652
min       17.000000  1.228500e+04  ...        1.000000      0.000000
25%       28.000000  1.178270e+05  ...       40.000000      0.000000
50%       37.000000  1.783560e+05  ...       40.000000      0.000000
75%       48.000000  2.369930e+05  ...       45.000000      0.000000
max       90.000000  1.484705e+06  ...       99.000000      1.000000

[8 rows x 8 columns]

In [18]:
print("Unique values and their counts for categorical columns:")
for col in categorical_cols:
    print(f"\nColumn: {col}")
    print(adult[col].value_counts())

Unique values and their counts for categorical columns:

Column: Workclass
Workclass
Private             24509
Self-emp-not-inc     2540
Local-gov            2093
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: count, dtype: int64

Column: marital_status
marital_status
Married-civ-spouse       14970
Never-married            10667
Divorced                  4441
Separated                 1025
Widowed                    993
Married-spouse-absent      418
Married-AF-spouse           23
Name: count, dtype: int64

Column: Occupation
Occupation
Prof-specialty       5979
Craft-repair         4094
Exec-managerial      4065
Adm-clerical         3768
Sales                3650
Other-service        3291
Machine-op-inspct    2000
Transport-moving     1597
Handlers-cleaners    1369
Farming-fishing       992
Tech-support          927
Protective-serv       649
Priv-house-serv       147
Armed-Forces            9
Name: count, dtype: int64

Column: Relationship
Relationship
Husband           13187
Not-in-family      8292
Own-child          5064
Unmarried          3445
Wife               1568
Other-relative      981
Name: count, dtype: int64

Column: Race
Race
White                 27795
Black                  3122
Asian-Pac-Islander     1038
Amer-Indian-Eskimo      311
Other                   271
Name: count, dtype: int64

Column: Country
Country
United-States                 29735
Mexico                          639
Philippines                     198
Germany                         137
Canada                          121
Puerto-Rico                     114
El-Salvador                     106
India                           100
Cuba                             95
England                          90
Jamaica                          81
South                            80
China                            75
Italy                            73
Dominican-Republic               70
Vietnam                          67
Guatemala                        62
Japan                            62
Poland                           60
Columbia                         59
Taiwan                           51
Haiti                            44
Iran                             43
Portugal                         37
Nicaragua                        34
Peru                             31
France                           29
Greece                           29
Ecuador                          28
Ireland                          24
Hong                             20
Cambodia                         19
Trinadad&Tobago                  19
Thailand                         18
Laos                             18
Yugoslavia                       16
Outlying-US(Guam-USVI-etc)       14
Honduras                         13
Hungary                          13
Scotland                         12
Holand-Netherlands                1
Name: count, dtype: int64

In [19]:
def group_marital(status):
    status = str(status).strip()
    if 'Married' in status:
        return 2  # married
    elif 'Never-married' in status:
        return 0  # Never-married
    else:
        return 1  # other

adult['marital_status'] = adult['marital_status'].apply(group_marital)

In [20]:
occ_counts = adult['Occupation'].value_counts()
adult['Occupation'] = adult['Occupation'].map(occ_counts)

In [21]:
from sklearn.preprocessing import LabelEncoder

# Apply label encoding to 'Relationship' column
adult['Relationship'] = LabelEncoder().fit_transform(adult['Relationship'].astype(str))

In [22]:
# if country is us 1, otherwise 0
adult['is_US'] = adult['Country'].apply(lambda x: 1 if str(x).strip() == 'United-States' else 0)

# Drop it
adult.drop('Country', axis=1, inplace=True)

In [23]:
print(f"Shape before re-encoding: {adult.shape}")

categorical_cols = adult.select_dtypes(include='object').columns

# Apply one-hot encoding to remaining categorical features
adult_encoded = pd.get_dummies(adult, columns=categorical_cols, drop_first=True)

print(f"Shape after one-hot encoding: {adult_encoded.shape}")
display(adult_encoded.head())

Shape before re-encoding: (32537, 14)
Shape after one-hot encoding: (32537, 23)

   Age  Fnlwgt  Education_num  ...  Race_ Black  Race_ Other  Race_ White
0   39   77516             13  ...        False        False         True
1   50   83311             13  ...        False        False         True
2   38  215646              9  ...        False        False         True
3   53  234721              7  ...         True        False        False
4   28  338409             13  ...         True        False        False

[5 rows x 23 columns]

In [24]:
categorical_cols = adult.select_dtypes(include='object').columns

plt.figure(figsize=(20, 25))
for i, col in enumerate(categorical_cols):
    plt.subplot(6, 3, i + 1) # Adjust subplot grid as needed
    sns.countplot(data=adult, x=col, palette='viridis')
    plt.title(f'Distribution of {col}')
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
plt.show()

### Feature Selection and Correlation Analysis

Now, we'll examine the correlation between the numerical features and the target variable (`Income`) to identify the most predictive features and check for multicollinearity.

In [25]:
import seaborn as sns
import matplotlib.pyplot as plt

# Calculate correlation matrix for numerical features and Income
corr_matrix = adult.corr(numeric_only=True)

plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title('Correlation Matrix of Numerical Features')
plt.show()

### Preparing X and y for Modeling

We will separate the features ($X$) and the target ($y$). We'll also drop `Fnlwgt` as it is an administrative weight and typically doesn't hold predictive value for individual income levels in this context.

In [26]:
# Define target and features
y_train = adult_encoded['Income']

# Dropping Fnlwgt as it is usually not a useful predictor for this dataset
X_train = adult_encoded.drop(columns=['Income', 'Fnlwgt'])

### Feature Scaling

To ensure our model treats all features fairly regardless of their original magnitude, we will scale the numerical columns using `StandardScaler`.

In [27]:
from sklearn.preprocessing import StandardScaler

# Identify numerical columns in the feature set (excluding the one-hot encoded ones)
num_cols = ['Age', 'Education_num', 'capital_gain', 'capital_loss', 'hours_per_week']

scaler = StandardScaler()

# Fit on training data and transform both training and testing sets
X_train_scaled = X_train.copy()

X_train_scaled[num_cols] = scaler.fit_transform(X_train[num_cols])

X_train_scaled.head(5)

        Age  Education_num  ...  Race_ Other  Race_ White
0  0.030390       1.134777  ...        False         True
1  0.836973       1.134777  ...        False         True
2 -0.042936      -0.420679  ...        False         True
3  1.056950      -1.198407  ...        False        False
4 -0.776193       1.134777  ...        False        False

[5 rows x 21 columns]

### Exporting Processed Data

Finally, we save the prepared training and testing sets to CSV files for use in the modeling phase.

In [28]:
# Saving processed datasets
X_train_scaled.to_csv('adult_X_train_processed.csv', index=False)
y_train.to_csv('adult_y_train_processed.csv', index=False)

print("Datasets saved successfully: X_train_processed.csv, y_train.csv")

Datasets saved successfully: X_train_processed.csv, y_train.csv

## Preprocessing adult.test Dataset

### Step 1: Load adult.test

In [29]:
adult_test = pd.read_csv('../data/adult.test', header=None, skiprows=1)
print(f"Original shape: {adult_test.shape}")
adult_test.head()

Original shape: (16281, 15)

   0           1       2              3   ...  11  12              13       14
0  25     Private  226802           11th  ...   0  40   United-States   <=50K.
1  38     Private   89814        HS-grad  ...   0  50   United-States   <=50K.
2  28   Local-gov  336951     Assoc-acdm  ...   0  40   United-States    >50K.
3  44     Private  160323   Some-college  ...   0  40   United-States    >50K.
4  18           ?  103497   Some-college  ...   0  30   United-States   <=50K.

[5 rows x 15 columns]

### Step 2: Rename columns to match training data

In [30]:
adult_test = adult_test.rename(columns={0:'Age', 1:'Workclass', 2:'Fnlwgt', 3:'Education', 4:'Education_num',
                              5:'marital_status', 6:'Occupation', 7:'Relationship',
                              8:'Race', 9:'Sex', 10:'capital_gain', 11:'capital_loss', 12:'hours_per_week',
                              13:'Country', 14:'Income'})
adult_test.head(5)

   Age   Workclass  Fnlwgt  ... hours_per_week         Country   Income
0   25     Private  226802  ...             40   United-States   <=50K.
1   38     Private   89814  ...             50   United-States   <=50K.
2   28   Local-gov  336951  ...             40   United-States    >50K.
3   44     Private  160323  ...             40   United-States    >50K.
4   18           ?  103497  ...             30   United-States   <=50K.

[5 rows x 15 columns]

### Step 3: Drop Education column

In [31]:
adult_test = adult_test.drop(columns=['Education'])
print(f"Shape after dropping Education: {adult_test.shape}")

Shape after dropping Education: (16281, 14)

### Step 4: Encode Income (remove trailing period and convert to binary)

In [32]:
adult_test['Income'] = adult_test['Income'].str.strip().str.rstrip('.')
adult_test['Income'] = adult_test['Income'].replace(['<=50K', '>50K'], [0, 1]).astype(int)
print("Income value counts:")
print(adult_test['Income'].value_counts())

Income value counts:
Income
0    12435
1     3846
Name: count, dtype: int64

### Step 5: Encode Sex (Male=1, Female=0)

In [33]:
adult_test['Sex'] = adult_test['Sex'].str.strip().map({'Male': 1, 'Female': 0})
print("Sex value counts:")
print(adult_test['Sex'].value_counts())

Sex value counts:
Sex
1    10860
0     5421
Name: count, dtype: int64

### Step 6: Remove duplicates

In [34]:
print(f"Number of duplicates: {adult_test.duplicated().sum()}")
adult_test.drop_duplicates(inplace=True)
print(f"Shape after removing duplicates: {adult_test.shape}")

Number of duplicates: 5
Shape after removing duplicates: (16276, 14)

### Step 7: Handle missing values (replace '?' with mode)

In [35]:
for col in ['Workclass', 'Occupation', 'Country']:
    adult_test[col] = adult_test[col].replace(' ?', np.nan)
    mode_value = adult_test[col].mode()[0]
    adult_test[col] = adult_test[col].fillna(mode_value)
    print(f"Missing values in '{col}' after imputation: {adult_test[col].isnull().sum()}")

Missing values in 'Workclass' after imputation: 0
Missing values in 'Occupation' after imputation: 0
Missing values in 'Country' after imputation: 0

### Step 8: Group marital status

In [36]:
adult_test['marital_status'] = adult_test['marital_status'].apply(group_marital)
print("Marital status value counts:")
print(adult_test['marital_status'].value_counts())

Marital status value counts:
marital_status
2    7626
0    5431
1    3219
Name: count, dtype: int64

### Step 9: Encode Occupation (map to frequency counts)

In [37]:
occ_counts = adult_test['Occupation'].value_counts()
adult_test['Occupation'] = adult_test['Occupation'].map(occ_counts)

### Step 10: Label encode Relationship

In [38]:
adult_test['Relationship'] = LabelEncoder().fit_transform(adult_test['Relationship'].astype(str))

### Step 11: Create is_US feature and drop Country

In [39]:
adult_test['is_US'] = adult_test['Country'].apply(lambda x: 1 if str(x).strip() == 'United-States' else 0)
adult_test.drop('Country', axis=1, inplace=True)

# One-hot encode remaining categorical features
categorical_cols = adult_test.select_dtypes(include='object').columns
adult_test_encoded = pd.get_dummies(adult_test, columns=categorical_cols, drop_first=True)

print(f"Shape after encoding: {adult_test_encoded.shape}")
display(adult_test_encoded.head())

Shape after encoding: (16276, 23)

   Age  Fnlwgt  Education_num  ...  Race_ Black  Race_ Other  Race_ White
0   25  226802              7  ...         True        False        False
1   38   89814              9  ...        False        False         True
2   28  336951             12  ...        False        False         True
3   44  160323             10  ...         True        False        False
4   18  103497             10  ...        False        False         True

[5 rows x 23 columns]

### Step 12: Scale numerical features and prepare for evaluation

In [40]:
# Separate target and features
y_test = adult_test_encoded['Income']
X_test = adult_test_encoded.drop(columns=['Income', 'Fnlwgt'])

# Scale numerical features
scaler_test = StandardScaler()
X_test_scaled = X_test.copy()
X_test_scaled[num_cols] = scaler_test.fit_transform(X_test[num_cols])

# Save processed test datasets
X_test_scaled.to_csv('adult_X_test_processed.csv', index=False)
y_test.to_csv('adult_y_test_processed.csv', index=False)

print(f"Test set shape: X_test={X_test_scaled.shape}, y_test={y_test.shape}")
print("\nTest datasets saved successfully:")
print("  - adult_X_test_processed.csv")
print("  - adult_y_test_processed.csv")
X_test_scaled.head()

Test set shape: X_test=(16276, 21), y_test=(16276,)

Test datasets saved successfully:
  - adult_X_test_processed.csv
  - adult_y_test_processed.csv

        Age  Education_num  ...  Race_ Other  Race_ White
0 -0.994356      -1.196669  ...        False        False
1 -0.055664      -0.417699  ...        False         True
2 -0.777734       0.750757  ...        False         True
3  0.377579      -0.028214  ...        False        False
4 -1.499805      -0.028214  ...        False         True

[5 rows x 21 columns]

In [41]:
print("Shape: ", X_train.shape)
print("Shape test: ", X_test.shape)

Shape:  (32537, 21)
Shape test:  (16276, 21)